name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 16 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Token
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: Decordy
          template: classic
          config_timezone: Europe/Paris
          base: header, community
          config_display: columns
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_indepth: yes
          plugin_notable_self: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_music_token: ${{ secrets.YOUTUBE_MUSIC_TOKENS }}
          plugin_music: yes
          plugin_music_mode: recent
          plugin_music_provider: youtube
          plugin_music_time_range: short
          plugin_music_played_at: yes
          plugin_music_limit: 4
          plugin_languages: yes
          # plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 16
          plugin_languages_sections: most-used
          plugin_fortune: yes
        prod:
          skip: true
